version: '3.1'
services:
  backend:
    image: 'gcr.io/<your repo here>/rbsps:<version>'
    env_file:
      - 'rbsps.env'
    ports:
      - '9000:9000'
  frontend:
    depends_on:
      - 'backend'
    image: 'gcr.io/<your repo here>/rbsps-nginx:1.11'
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
